/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "kpm_v3.asn"
 * 	`asn1c -D ./e2sm`
 */

#ifndef	_E2SM_KPM_IndicationMessage_H_
#define	_E2SM_KPM_IndicationMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "E2SM-KPM-IndicationMessage-Format1.h"
#include "E2SM-KPM-IndicationMessage-Format2.h"
#include "E2SM-KPM-IndicationMessage-Format3.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum indicationMessage_formats_PR {
	indicationMessage_formats_PR_NOTHING,	/* No components present */
	indicationMessage_formats_PR_indicationMessage_Format1,
	indicationMessage_formats_PR_indicationMessage_Format2,
	/* Extensions may appear below */
	indicationMessage_formats_PR_indicationMessage_Format3
} indicationMessage_formats_PR;

/* E2SM-KPM-IndicationMessage */
typedef struct E2SM_KPM_IndicationMessage {
	struct indicationMessage_formats {
		indicationMessage_formats_PR present;
		union E2SM_KPM_IndicationMessage__indicationMessage_formats_u {
			E2SM_KPM_IndicationMessage_Format1_t	 indicationMessage_Format1;
			E2SM_KPM_IndicationMessage_Format2_t	 indicationMessage_Format2;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			E2SM_KPM_IndicationMessage_Format3_t	 indicationMessage_Format3;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} indicationMessage_formats;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_KPM_IndicationMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2SM_KPM_IndicationMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_KPM_IndicationMessage_H_ */
#include <asn_internal.h>
